// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfAmcwrdUG14u5NoqMPuMSsvkDBVbzkY',
    appId: '1:630806884551:web:0b749dceefefbd74854ee2',
    messagingSenderId: '630806884551',
    projectId: 'flutterstorage-4e2ed',
    authDomain: 'flutterstorage-4e2ed.firebaseapp.com',
    storageBucket: 'flutterstorage-4e2ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vS9ZgNhrzRWCgaPJYaDrn64iphqjQes',
    appId: '1:630806884551:android:540a8980d2382595854ee2',
    messagingSenderId: '630806884551',
    projectId: 'flutterstorage-4e2ed',
    storageBucket: 'flutterstorage-4e2ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBci2QDX-yQWT_1VHwcwJkI2od7T3_Bckw',
    appId: '1:630806884551:ios:ab02d66789e32d25854ee2',
    messagingSenderId: '630806884551',
    projectId: 'flutterstorage-4e2ed',
    storageBucket: 'flutterstorage-4e2ed.appspot.com',
    iosClientId: '630806884551-u3dju40nk3t1q3ac77bh03kqcpb0hafl.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafe1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBci2QDX-yQWT_1VHwcwJkI2od7T3_Bckw',
    appId: '1:630806884551:ios:ab02d66789e32d25854ee2',
    messagingSenderId: '630806884551',
    projectId: 'flutterstorage-4e2ed',
    storageBucket: 'flutterstorage-4e2ed.appspot.com',
    iosClientId: '630806884551-u3dju40nk3t1q3ac77bh03kqcpb0hafl.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafe1',
  );
}
